website/views.py
from flask import Blueprint, render_template, request, flash, redirect
import pandas as pd
import csv, sqlite3
from datetime import datetime
import numpy as np
import requests
import json
from website.static.countries import countryMap as country_codes
views = Blueprint('views', __name__)

PAYPAL_RATES = 0.980728390317
STRIPE_NON_EU = 0.962
STRIPE_EU = 0.979551012
SHOPIFY = 217.57
EURO_COUNTRIES = {"Austria",
                  "Belgium",
                  "Croatia",
                  "Cyprus",
                  "Estonia",
                  "Finland",
                  "France",
                  "Germany",
                  "Greece",
                  "Ireland",
                  "Italy",
                  "Latvia",
                  "Lithuania",
                  "Luxembourg",
                  "Malta",
                  "Netherlands",
                  "Portugal",
                  "Slovakia",
                  "Slovenia",
                  "Spain"}
country=['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Republic of Cyprus', 'Czech Republic',
'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy',
'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania',
'Slovakia', 'Slovenia', 'Spain' , 'Sweden']

MONTHS = {
    0: "Jan",
    1: "Feb",
    2: "Mar",
    3: "Apr",
    4: "May",
    5: "June",
    6: "July",
    7: "Aug",
    8: "Sep",
    9: "Oct",
    10: "Nov",
    11: "Dec",
}


@views.route('/', methods=['GET', 'POST'])
def payouts():
    if request.method == "GET":
        return render_template(
            "payouts_form.html"
        )
    if 'file' not in request.files:
        flash('No file part')
        return redirect(request.url)
    sales = request.files['file']
    payments = request.files['file_payments']
    ad_ss = float(request.form.get("ad-expenses"))
    ad_doxed = float(request.form.get("ad-expenses-doxed"))
    store_expenses = float(request.form.get("store-expenses"))

    if sales.filename == '' or payments.filename == '':
        flash('No selected file')
        return redirect(request.url)
    if sales and allowed_file(sales.filename) and payments and allowed_file(payments.filename):
        df_sales = pd.read_csv(sales)
        df_payments = pd.read_csv(payments)
        conn = sqlite3.connect("identifier.sqlite")
        df_sales_new = pd.merge(df_sales, df_payments, on='Order')
        df_sales_new = df_sales_new.drop_duplicates(subset=["Sale ID"], keep=False)
        df_sales_new.to_sql("earnings", conn, if_exists='append', index=False)
        datestring = pd.to_datetime(df_sales["Date"].values[:1])
        year = datestring.year.values[0].astype(str)
        month = datestring.month.values[0].astype(str)
        mycursor = conn.cursor()
        try:
            mycursor.execute(
                "REPLACE INTO expenses (year, month, ads_ss, ads_doxed, store_expenses) VALUES (?, ?, ?,?,?)",
                (year, month, ad_ss, ad_doxed, store_expenses))
            conn.commit()
        except:
            print("exists")
        conn.close()
        flash('Success!')
        return redirect(request.url)

    flash('Not a CSV file')
    return redirect(request.url)

@views.route('/test', methods=['GET', 'POST'])
def test():
    return render_template(
        "test.html"
    )
@views.route('/analytics', methods=['GET', 'POST'])
def analytics():
    conn = sqlite3.connect("identifier.sqlite")
    cur = conn.cursor()
    cur.execute("SELECT * FROM expenses")
    date_data = []
    rows = cur.fetchall()
    for row in rows:
        date_data.append([row[0], MONTHS[int(row[1]) - 1]])
    cur = conn.cursor()
    dates_placeholder=""
    month_from = 0
    month_to = 0
    year_from = 0
    year_to = 0
    if request.method == "GET":
        data = pd.read_sql(sql="SELECT * FROM earnings",con=conn)
    else:
        dates_placeholder = request.form.get("dates")
        dates = request.form.get("dates").split(" to ")
        if len(dates) == 1:
            flash('Error')
            return render_template(
                "analytics_error.html"
            )
        date_from = dates[0].split("/")
        year_from = int("20"+date_from[2])
        month_from = int(date_from[1])
        date_from = "20"+date_from[2]+"-"+date_from[1]+"-"+date_from[0]
        date_to = dates[1].split("/")
        year_to = int("20"+date_to[2])
        month_to = int(date_to[1])
        date_to = "20"+date_to[2]+"-"+date_to[1]+"-"+date_to[0]
        print(date_from,date_to)
        data = pd.read_sql(sql="SELECT * FROM earnings WHERE strftime('%Y-%m-%d', Date_x) BETWEEN ? AND ?", con=conn, params=(date_from,date_to))
    df = pd.DataFrame(data)
    if not df.empty:
        total_sales = df['Total sales'].sum()
        df['In Eu'] = df.apply(lambda x: x['Billing country'] in country, axis=1)
        result = df.groupby("In Eu").sum()
        in_eu = result.iloc[1]['Net sales']
        not_in_eu = result.iloc[0]['Net sales']
        eu_data = [in_eu,not_in_eu]

        df = pd.DataFrame(data)
        df = df.groupby("Billing country").sum()
        df = df.sort_values(['Total sales'], ascending=False)
        df = df.head(10)
        countries = list(df.index.values)
        sales_by_country = df["Total sales"].tolist()
        country_data = []
        for i in range(len(countries)):
            country_data.append((countries[i], sales_by_country[i],"https://flagcdn.com/16x12/"+country_codes[countries[i]].lower()+".png"))

        df = pd.DataFrame(data)
        df = df.groupby("Billing city").sum()
        df = df.sort_values(['Total sales'], ascending=False)
        df = df.head(10)
        cities = list(df.index.values)
        sales_by_city = df["Total sales"].tolist()
        city_data = [cities,sales_by_city]

        df = pd.DataFrame(data)
        df = df.groupby("Product").sum()
        df = df.sort_values(['Total sales'], ascending=False)
        df = df.head(10)
        products = list(df.index.values)
        sales_by_product = df["Total sales"].tolist()
        product_data = []
        for i in range(len(products)):
            product_data.append((products[i], sales_by_product[i]))
        cur = conn.cursor()
        if request.method == "POST":
            cur.execute("SELECT * FROM expenses WHERE CAST(year AS INTEGER) >= ? AND CAST(year AS INTEGER) <= ? AND CAST(month AS INTEGER) >= ? AND CAST(month AS INTEGER) <= ?",(year_from,year_to,month_from,month_to))
        else:
            cur.execute("SELECT * FROM expenses")
        rows = cur.fetchall()
        ad_expenses = 0
        for row in rows:
            ad_expenses += row[2]
            ad_expenses += row[3]
            ad_expenses += row[4]
        df = pd.DataFrame(data)
        stripe_eu_total, stripe_non_eu_total, total_paypal, total_earnings = calculate_from_df(df)
        total_store = SHOPIFY + total_earnings * 0.02
        total_stripe = stripe_non_eu_total + stripe_eu_total

        total_expenses_payment = total_stripe + total_paypal
        total_net = total_earnings - total_stripe - total_paypal - total_store - ad_expenses

        df = pd.DataFrame(data)
        df["Product"] = df['Product'].str.split(' - ', n=1)
        df["Product"] = df['Product'].apply(lambda x: x if x is None else x[0])
        df["Product"] = df['Product'].apply(lambda x: "SLCTD collections." if x =="SLCTD collections" else x)
        df["Product"] = df['Product'].apply(lambda x: "Sickrate & SIIK Essentials I" if x =="Sickrate & SIIK Essentials" else x)

        df = df.groupby("Product").sum()
        df = df.sort_values(['Total sales'], ascending=False)
        products = list(df.index.values)
        sales_by_product = df["Total sales"].tolist()
        product_data_merged = []
        for i in range(len(products)):
            product_data_merged.append((products[i], sales_by_product[i]))
        return render_template(
        "analytics.html", date_data=date_data,eu_data=eu_data,country_data=country_data,city_data=city_data,total_sales=total_sales, product_data=product_data,dates=dates_placeholder,total_earnings=total_earnings,total_net=total_net,product_data_merged=product_data_merged,total_expenses_payment=total_expenses_payment,total_store=total_store
    )
    else:
        flash('No purchases in date range')

        return render_template(
            "analytics_error.html"
        )


@views.route('/payouts', methods=['GET', 'POST'])
def payouts_description():
    conn = sqlite3.connect("identifier.sqlite")
    args = request.args
    year = args.get("year", default="", type=str)
    month = args.get("month", default="", type=str)
    month = str(list(MONTHS.keys())[list(MONTHS.values()).index(month)] + 1)

    cur = conn.cursor()
    cur.execute("SELECT * FROM expenses WHERE year = ? AND month = ?", (year, month))
    rows = cur.fetchone()
    ad_ss = float(rows[2])
    ad_doxed = float(rows[3])

    store_expenses = float(rows[4])

    month_clean = month
    if len(month) < 2:
        month_clean = "0" + month_clean
    print(year, month)
    data = pd.read_sql(sql="SELECT * FROM earnings WHERE strftime('%Y', Date_x) = ? AND strftime('%m',Date_x) = ?",
                       con=conn, params=(year, month_clean,))

    df = pd.DataFrame(data)
    df_sickrate = df[df["Product"].str.contains("Sickrate", na=False) | df["Product"].str.contains("SLCTD", na=False)]
    stripe_eu_total_sickrate, stripe_non_eu_total_sickrate,paypal_total_sickrate,earnings_sickrate = calculate_from_df(df_sickrate)
    store_expenses_sickrate = earnings_sickrate*0.02/2 + SHOPIFY/2 + store_expenses/2

    df_doxed = df[df["Product"].str.contains("Doxed", na=False)]
    stripe_eu_total_doxed, stripe_non_eu_total_doxed,paypal_total_doxed,earnings_doxed = calculate_from_df(df_doxed)
    store_expenses_doxed = earnings_doxed*0.02/2
    store_expenses_siik = earnings_doxed*0.02/2  + earnings_sickrate*0.02/2  + SHOPIFY/2

website/templates/analytics_error.html
{% extends "base.html" %}
    <link rel="apple-touch-icon" sizes="180x180" href="../static/assets/img/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../static/assets/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../static/assets/img/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicons/favicon.ico">
    <link rel="manifest" href="../static/assets/img/favicons/manifest.json">
    <meta name="msapplication-TileImage" content="../static/assets/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">
    <script src="../static/vendors/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="../static/vendors/simplebar/simplebar.min.js"></script>
    <script src="../static/assets/js/config.js"></script>


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&amp;display=swap" rel="stylesheet">
    <link href="../static/vendors/simplebar/simplebar.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link href="../static/assets/css/theme-rtl.min.css" type="text/css" rel="stylesheet" id="style-rtl">
    <link href="../static/assets/css/theme.min.css" type="text/css" rel="stylesheet" id="style-default">
    <link href="../static/assets/css/user-rtl.min.css" type="text/css" rel="stylesheet" id="user-style-rtl">
    <link href="../static/assets/css/user.min.css" type="text/css" rel="stylesheet" id="user-style-default">
{% block title %} Analytics {% endblock %}
{% block content %}
    <script src="../static/vendors/popper/popper.min.js"></script>
    <script src="../static/vendors/bootstrap/bootstrap.min.js"></script>
    <script src="../static/vendors/anchorjs/anchor.min.js"></script>
    <script src="../static/vendors/is/is.min.js"></script>
    <script src="../static/vendors/fontawesome/all.min.js"></script>
    <script src="../static/vendors/lodash/lodash.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="../static/vendors/list.js/list.min.js"></script>
    <script src="../static/vendors/feather-icons/feather.min.js"></script>
    <script src="../static/vendors/dayjs/dayjs.min.js"></script>
    <script src="../static/vendors/echarts/echarts.min.js"></script>
    <script src="../static/vendors/prism/prism.js"></script>
    <script src="../static/assets/js/phoenix.js"></script>
        <script src="../static/assets/js/flatpickr.js"></script>
        <link href="../static/vendors/flatpickr/flatpickr.min.css" rel="stylesheet" />
          <div class="content">
        <div class="pb-5">
          <div class="row">
            <div class="col">
              <div class="mb-8">
                <h1>Analytics</h1>
                <h5 class="text-700 fw-semi-bold">Insights into SIIK Sounds</h5>
              </div>
            </div>
              <div class="col">

              </div>
          </div>
<div class="container">

                <div class="row mb-10">
                    <form method="post">
                        <label class="form-label" for="timepicker2">Select Time Range</label>
                        <input name="dates" class="form-control datetimepicker flatpickr-input" id="timepicker2" type="text" placeholder="d/m/y to d/m/y" data-options="{&quot;mode&quot;:&quot;range&quot;,&quot;dateFormat&quot;:&quot;d/m/y&quot;,&quot;disableMobile&quot;:true}" readonly="readonly">
                        <input type="submit" class="btn btn-primary w-25 mt-2" />
                    </form>

                </div>

            </div>
        </div>
          </div>
{% endblock %}

website/templates/analytics_form.html
{% extends "base.html" %}
{% block title %} Payouts Calculator {% endblock %}
{% block content %}
<form method="POST">
    <h3>Load CSV with Shopify Data for Analytics</h3>
    <div class="form-group">
        <label for="file">CSV File</label>
        <input type="file" id="file" name="csv-file"/>
        <button type="submit">Submit</button>
    </div>
</form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="apple-touch-icon" sizes="180x180" href="../static/assets/img/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../static/assets/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../static/assets/img/favicons/favicon-16x16.png">
    <link rel="shortcut icon" type="image/x-icon" href="../static/assets/img/favicons/favicon.ico">
    <link rel="manifest" href="../static/assets/img/favicons/manifest.json">
    <meta name="msapplication-TileImage" content="../static/assets/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">
    <script src="../static/vendors/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="../static/vendors/simplebar/simplebar.min.js"></script>
    <script src="../static/assets/js/config.js"></script>


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&amp;display=swap" rel="stylesheet">
    <link href="../static/vendors/simplebar/simplebar.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link href="../static/assets/css/theme-rtl.min.css" type="text/css" rel="stylesheet" id="style-rtl">
    <link href="../static/assets/css/theme.min.css" type="text/css" rel="stylesheet" id="style-default">
    <link href="../static/assets/css/user-rtl.min.css" type="text/css" rel="stylesheet" id="user-style-rtl">
    <link href="../static/assets/css/user.min.css" type="text/css" rel="stylesheet" id="user-style-default">
    <script>
      var phoenixIsRTL = window.config.config.phoenixIsRTL;
      if (phoenixIsRTL) {
        var linkDefault = document.getElementById('style-default');
        var userLinkDefault = document.getElementById('user-style-default');
        linkDefault.setAttribute('disabled', true);
        userLinkDefault.setAttribute('disabled', true);
        document.querySelector('html').setAttribute('dir', 'rtl');
      } else {
        var linkRTL = document.getElementById('style-rtl');
        var userLinkRTL = document.getElementById('user-style-rtl');
        linkRTL.setAttribute('disabled', true);
        userLinkRTL.setAttribute('disabled', true);
      }
    </script>
    <link href="../static/vendors/leaflet/leaflet.css" rel="stylesheet">
    <link href="../static/vendors/leaflet.markercluster/MarkerCluster.css" rel="stylesheet">
    <link href="../static/vendors/leaflet.markercluster/MarkerCluster.Default.css" rel="stylesheet">
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Upload Data</a>
            <a class="nav-item nav-link" id="home" href="/analytics">Analytics</a>
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/payouts_form.html
{% extends "base.html" %}
{% block title %} Payouts Calculator {% endblock %}
{% block content %}
<form method="POST" enctype=multipart/form-data>
    <div class="content">
        <h1>Load CSV with Shopify Data for Payouts</h1>
        <h5>Load only exported by single month!</h5>
    <div class="form-group">

      <div class="mb-3">
        <label class="form-label" for="file">Sales CSV</label>
        <input class="form-control" required type="file" id="file" name="file">
      </div>

        <div class="mb-3">
        <label class="form-label" for="file_payments">Payments By Type CSV</label>
        <input class="form-control" required type="file" id="file_payments" name="file_payments">
      </div>
        <div class="mb-3">
            <label for="ad-expenses">Ad Expenses Sickrate & SIIK(€)</label>
            <input class="form-control form-control-sm" step="0.01" required type="number" id="ad-expenses" name="ad-expenses" placeholder="150"/>
        </div>
        <div class="mb-3">
            <label for="ad-expenses-doxed">Ad Expenses Doxed(€)</label>
            <input class="form-control form-control-sm" step="0.01" required type="number" id="ad-expenses-doxed" name="ad-expenses-doxed" placeholder="150"/>
        </div>
        <div class="mb-3">
        <label for="store-expenses">Other Expenses(€)</label>
        <input class="form-control form-control-sm" required step="0.01" type="number" id="store-expenses" name="store-expenses" placeholder="150"/>
        </div>

        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
    </div>

</form>
{% endblock %}

website/templates/test.html
<div>
    <div class="container">
        <h1>Payouts in months</h1>
            <div class="row">
            {% for date in date_data %}
                <a href="{{ url_for('views.payouts_description', year=date[0], month=date[1])}}">
                    <div class="col-md-3 m-2">
                        <div class="card" style="width: 18rem;">
                          <div class="card-body">
                            <h5 class="card-title">{{ date[0] }} {{ date[1] }}</h5>
                            <p class="card-text">Payouts</p>
                          </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</div>